### ISSUE TITLE
Rapid Releases

### ISSUE THREAD

**Issue by EdJoPaTo** [ratatui/ratatui#1232] opened 2024-07-17 11:18 UTC
## Problem

Currently releases are further apart and features and especially bug fixes take time until they are released.

While Alpha releases are automated they are mostly pointless and nearly unused (see graph at the bottom of https://crates.io/crates/ratatui)

## Solution

The alpha is just the main branch. Cargo supports this natively anyway so why not promote this instead.

The existing release automation could just instead publish bugfix and feature releases unless there are breaking changes. Maybe have them trigger manually but do the rest automated like the alpha releases can currently.

This way there are more often releases and features and bug fixes are quicker at the users.

## Additional thoughts

Consider a 1.0.0 release. Currently breaking changes are prevented like it's a stable crate but the current server scheme 0.x.y suggests it's not stable yet. Release numbers would be more clear with a x.y.z version. Breaking change releases are not a big problem and versions starting with higher numbers are fine.

**Comment by orhun** [comment] 2024-07-27 06:02
First of all, thanks for bringing this up. Release automation is one of the topics I like to brainstorm and discuss a lot!

Before we delve into everything, let me review our current release process by examining its pros and cons to get a clearer picture of how things have been working thus far. I would say our release philosophy has been:

> _Release every 1-1.5 months with a detailed summary, along with automated alpha releases every week_.

### Release Workflow

1. Bump the version and update the changelog via `git-cliff`: https://github.com/ratatui-org/ratatui/pull/1196
2. Prepare a small write-up for the notable changes: https://github.com/ratatui-org/ratatui-website/pull/644
3. Pick a good time, release it, and announce it on Discord, Twitter, Mastodon, LinkedIn, Reddit, TWIR, HackerNews, and Lobsters.

#### Pros

- Every new feature, fix, or breaking change is well-documented through the summary and changelog.
- The content is beneficial for people visiting the website.
- Reduced possibility of regression (debatable).

#### Cons

- Takes time to complete a release due to manual work.
- Requires a social media plan/strategy – I don't think we can automate that.
- Large time gap between releases.

Alpha releases were intended for people who did not want to wait for a new release (and also for those who wanted to create a release on crates.io). It worked fine; I remember a couple of cases where people _really_ needed it. (e.g., @atuinsh used to depend on an RC release – it's definitely better than vendoring the whole Ratatui crate)

---

Now, how can we improve everything? Well, +1 to @joshka:

> It's possible that a good idea would be to just change our philosophy of releases to generally release point releases like 0.27.1 weekly or whenever there's new stuff worth releasing, and save the larger full summaries for the major releases. Effectively transitioning off the alpha release approach.

It's a good idea. This will theoretically mean that our automated alpha releases will become semi-automated point/patch releases, and we can keep writing summaries for minor/major releases. I think we can just remove the cron and alpha release calculation from the CI and let it only run via `workflow_dispatch`. So:

### Proposed Release Workflow

> _Release major/minor versions with detailed summaries when necessary, while releasing point/patch versions weekly or as needed without extensive announcements._

#### Major/Minor Releases

These releases will usually contain breaking changes, so we can continue writing summaries.

The workflow will remain the same as above.

#### Patch Releases

1. Bump the version and update the changelog as before (we can use `git cliff --prepend CHANGELOG.md`).
2. Run the workflow (creates a release on GitHub and crates.io).

I'm guessing we don't need to announce these releases extensively, so this will be sufficient.

Let me know what you think! @ratatui-org/maintainers

**Comment by joshka** [comment] 2024-07-27 06:27
So one thing to note is that we'll have to be careful about breaking changes being merged to main in that world. Right now main is heading for a 0.28.0 release because it has breaking changes in it.

Something I'd like to think about more is how we move the manual release steps into normal running of the repo process so we're not dependent on someone doing the release notes specifically for a major release. Rephrased, what would it take for the repo to be in a state where we'd be comfortable cutting a 0.28.0 release right now with what we have?

I suspect this is where the automation currently breaks down. We likely don't have a criteria that could filter out commits that we don't care about on a case by case basis, and we don't have a good way to massage the changelog commit messages into a changelog that won't be overwritten by automation. There's no good way to mark a particular commit as  "git cliff leave this commit alone, it's clean" afaik.

Maybe git-cliff needs to be able to read the changelog and only append new commit info, or something like that? This would make it possible to build the release incrementally just as a normal part of working.

**Comment by orhun** [comment] 2024-07-27 18:10
> So one thing to note is that we'll have to be careful about breaking changes being merged to main in that world. Right now main is heading for a 0.28.0 release because it has breaking changes in it.

Yes, exactly. I'm planning to document this new approach in RELEASE.md and we can start cooking up 0.28.0 next week.

> what would it take for the repo to be in a state where we'd be comfortable cutting a 0.28.0 release right now with what we have?

I think we can simply skip the release summary (or c/p changelog entries) and go with the release as usual (bump the version and push the tag)

>  There's no good way to mark a particular commit as "git cliff leave this commit alone, it's clean" afaik.

Can you expand on what you mean here with an example?

> Maybe git-cliff needs to be able to read the changelog and only append new commit info, or something like that? This would make it possible to build the release incrementally just as a normal part of working.

There is `--prepend` option but it does not _read_ the changelog. FWIW it might support [parsing](https://github.com/orhun/git-cliff/issues/433) markdown in the future.

**Comment by joshka** [comment] 2024-07-28 00:32
> Can you expand on what you mean here with an example?

I meant that if you manually edit the changelog, and there's a clear boundary where a specific commit produces markdown, then it would be neat to be able to mark certain edits as "done" so that git-cliff only adds new commits etc. I effect I want a hybrid setup where it's possible to easily pre-prepare release notes even if the commits aren't the best source of the information. A somewhat hybrid approach that doesn't get in the way of the automation is difficult to do well though.

The prepend option is a part way solution, but I'm mostly speculating about what a full solution might look like.

**Comment by orhun** [comment] 2024-07-28 07:08
Hmm, definitely sounds interesting. I think the challenge might be making this possible without disrupting the automation. e.g. we need to prevent `git-cliff` from overwriting or duplicating these "marked-as-done" sections. Maybe some tags/comments inside the markdown document might be useful in regards to that. Happy to discuss it [here](https://github.com/orhun/git-cliff/discussions).

**Comment by orhun** [comment] 2024-08-04 09:20
Let's go with `0.28.0` release this week (possibly tomorrow). Are we on the same page that we want to remove alpha releases and create minor releases as we need them, without release highlights + more automation?

I will update `RELEASE.md` based on what we decide here :)

**Comment by EdJoPaTo** [comment] 2024-08-04 09:56
> Let's go with `0.28.0` release this week (possibly tomorrow).

There are a bunch of approved PRs that should get another review and getting merged before a release should happen.
https://github.com/ratatui-org/ratatui/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved

> Are we on the same page that we want to remove alpha releases and create minor releases as we need them, without release highlights + more automation?
> 
> I will update `RELEASE.md` based on what we decide here :)

I would prefer that! Easily releasable bugfix releases with as little manual stuff required for a release.

**Comment by orhun** [comment] 2024-08-04 19:15
Alright! I will do my best to review them thoroughly and cook up the release in the meantime. Is there anything crucial pending? We can leave the non-breaking ones for a minor release to not hold off 0.28.0 any longer.

**Comment by orhun** [comment] 2024-08-05 09:06
Created drafts:

- https://github.com/ratatui-org/ratatui-website/pull/673
- https://github.com/ratatui-org/ratatui/pull/1295

**Comment by orhun** [comment] 2024-08-07 08:23
Going ahead with the release today in a couple of hours, will get to updating `RELEASE.md` later on.

**Comment by joshka** [comment] 2024-08-08 03:26
Closed by mistake - likely best to keep this open for discussion.

**Closed** 2024-08-25 08:02 UTC
Labels: Type: Enhancement
