### ISSUE TITLE
Tab characters break Paragraph in mutliple ways

### ISSUE THREAD

**Issue by mcclure** [ratatui/ratatui#1366] opened 2024-09-11 18:16 UTC
When I put `\t` into my Paragraph text weird things happen.

## Repro

https://github.com/mcclure/rs-bug branch tui-tab-bug.

`cargo run` this. This is a fork of the "popup" sample. It displays [this string](https://github.com/mcclure/rs-bug/blob/tui-tab-bug/src/main.rs#L104) which contains a mix of `\t`s and `\n`s. Ignore the on screen instructions, the controls you care about are `a` (which turns trim on and off) and `s` (which replaces the entire on-screen text with some random keysmash).

You may find it also interesting to change line 44 so the default value of `trim` is different, I get different results (which I did not screenshot).

## Screenshots

Application, initially. It looks normal.

![image](https://github.com/user-attachments/assets/073b6e7c-3d69-4bb4-a7f4-6b72e5a4e380)

Hit `a` to enable alternate-text.

![image](https://github.com/user-attachments/assets/11b65933-91f9-47e0-8642-a34543c153fc)

It's supposed to look like that. Hit `a` again to restore the original text. Now hit `s`. This will have the current paragraph be displayed with `trim` off.

![image](https://github.com/user-attachments/assets/a7e1132e-74c7-4455-8381-b349e63596c1)

Now that `trim` is off, and the tabs are appearing… That looks weird. Hit `a` again to replace this text with the alt text.

![image](https://github.com/user-attachments/assets/b5927e9e-6fa8-4cd6-91ae-23d7b4a5f349)

This looks even weirder. Having displayed text with tabs just once broke the "dirty rectangles" of the triangle. Hit `a` again to restore the original text.

![image](https://github.com/user-attachments/assets/4f7c1a31-a6c1-429b-9bf7-69977937a7fe)

Oh no.

## Environment

OS: Ubuntu 24.04 LTS, 
Terminal Emulator: gnome-terminal
Font: ? Ubuntu default
Crate version: 0.28.1
Backend: I don't know what that means

**Comment by joshka** [comment] 2024-09-12 00:35
I think this is mostly a dupe of https://github.com/ratatui/ratatui/issues/876, but with some added weirdness.
Would you mind moving this info over there and closing this to keep the discussion in one issue?

**Closed** 2024-09-16 03:32 UTC
Labels: Type: Bug

**Comment by mcclure** [comment] 2024-09-18 22:18
Hi, sorry I missed your previous comment and thanks for doing the move.

**Comment by joshka** [comment] 2024-09-19 00:41
No probs :)
