### ISSUE TITLE
Rendering issue when increasing frame size beyond a certain point

### ISSUE THREAD

**Issue by YS-L** [ratatui/ratatui#1441] opened 2024-10-20 17:46 UTC
## Description

I'm encountering a rendering issue where the rendered text appears to "warp" around instead of being placed at the specified positions. The problem seems to manifest when the number of cells in the frame increases beyond a certain point (e.g. by reducing font size while maintaining the terminal's physical size).

## To Reproduce

I'm using this simple code based on `ratatui/templates` to fill the frame with short text.

```rust
    fn draw(&mut self, frame: &mut Frame) {
        let area = frame.area();
        let buf = frame.buffer_mut();
        for (i, y) in (area.y..area.bottom()).enumerate() {
            let s = if i == 0 {
                format!("Total area: {:?}", area.area())
            } else {
                format!("#{:02}", i)
            };
            buf.set_span(area.x, y, &Span::from(s.as_str()), s.len() as u16);
        }
    }
```

It should produce something simple like this, where the text is aligned to the left:

![Image](https://github.com/user-attachments/assets/06c9a0a1-dc13-4a7c-ad53-2c276e16fba5)

This works for typical frame sizes, but when increasing the frame size beyond a certain point, some of the text is rendered in the middle of the screen, which shouldn't happen since the code always specifies the same `area.x` as the x position.

## Expected behavior

All the text is aligned to the left regardless of frame size.

## Screenshots

It works as expected for a while, but something strange happens when the frame size exceeds a certain size (I suspect 65536):

![Image](https://github.com/user-attachments/assets/631b5089-73ec-4dc8-8576-ed331697dca6)

## Environment

- OS: Linux
- Terminal Emulator: xterm
- Font: Monospace Regular
- Crate version: main branch (514d2738750d792a75fde6cc7666f9220bcf6b3a)
- Backend: crossterm

## Additional context

* Same behavior when using v0.28.1

* Cannot reproduce when using v0.27.0, where it looks like this:
   ![Image](https://github.com/user-attachments/assets/490b6517-c5aa-4ea0-814f-6b1c3db814e8)

   It seems the area is capped below 65536 somehow, possibly due to area clamping that is now removed.

* I just realized that the `list` example in the repo might be affected by the same issue, though the symptoms are not exactly the same. This is what I get when the frame size is sufficiently large:
   ![Image](https://github.com/user-attachments/assets/7c308162-08ec-49ed-86e5-d47b724eb38d)

   which is quite different compared to the UI when rendered properly:
   ![Image](https://github.com/user-attachments/assets/4a354c4c-8b81-4ff8-b0f0-620065279f90)

**Comment by joshka** [comment] 2024-10-20 21:28
Please make the screenshot just a static one of where the issue is rather than what happens when moving to the issue. It's not clear which parts are just resizing artifacts from your terminal prior to re rendering from the gif. 

Also, check the problem against the main branch. We recently removed the area clamping to u16.

**Comment by JeromeSchmied** [comment] 2024-10-21 18:48
same for me with my [conway-life viewer](https://github.com/JeromeSchmied/cgol-tui-rs) using latest ratatui version from crates-io: v0.29.0

**system info**
```
OS: Arch Linux x86_64
Kernel: Linux 6.11.4-arch2-1
Shell: fish 3.7.1
Display (LG HDR 4K): 3840x2160 @ 30 Hz (as 1920x1080) in 27" [External]
WM: Sway (Wayland)
Cursor: Adwaita
Terminal: alacritty 0.13.2
Terminal Font: alacritty (14.8pt)
CPU: 11th Gen Intel(R) Core(TM) i3-1125G4 (8) @ 3.70 GHz
GPU: Intel UHD Graphics G4 @ 1.25 GHz [Integrated]
Locale: en_US.UTF-8
```

whole screen should be filled, it's weird instead.
issue screenshot:

![Image](https://github.com/user-attachments/assets/9165b580-9a25-474e-9dcf-e923f4d40d60)

**Comment by joshka** [comment] 2024-10-22 08:43
Repro'ed and fixed in PR https://github.com/ratatui/ratatui/pull/1447

**Closed** 2024-10-22 10:46 UTC
Labels: Type: Bug
